from pathlib import Path
import re

ROOT = Path('.')
java_dir = ROOT / 'app/src/main/java/com/cefalo/angulos'

# -----------------------------------------------------------------------------
# Identity: this is the dedicated lateral-skull application, not the full app.
# -----------------------------------------------------------------------------
gradle = ROOT / 'app/build.gradle'
g = gradle.read_text(encoding='utf-8')
g = re.sub(r"applicationId\s+'[^']+'", "applicationId 'com.yomceph.cefalometrico'", g, count=1)
g = re.sub(r'versionCode\s+\d+', 'versionCode 33', g, count=1)
g = re.sub(r"versionName\s+'[^']+'", "versionName '1.32'", g, count=1)
gradle.write_text(g, encoding='utf-8')

for path in [ROOT / 'app/src/main/res/values/strings.xml', ROOT / 'app/src/main/res/values-en/strings.xml']:
    s = path.read_text(encoding='utf-8')
    if 'values-en' in str(path):
        replacements = {
            'app_name': 'Yom lateral skull analysis',
            'app_slogan': 'Comprehensive lateral cephalometric analysis',
            'analysis_steiner': 'COMPREHENSIVE CEPHALOMETRIC ANALYSIS',
            'section_lateral': 'LATERAL SKULL RADIOGRAPH',
        }
    else:
        replacements = {
            'app_name': 'Yom análisis de lateral de cráneo',
            'app_slogan': 'Análisis cefalométrico integral',
            'analysis_steiner': 'ANÁLISIS CEFALOMÉTRICO INTEGRAL',
            'section_lateral': 'RADIOGRAFÍA LATERAL DE CRÁNEO',
        }
    for key, value in replacements.items():
        s = re.sub(
            rf'<string name="{re.escape(key)}">.*?</string>',
            f'<string name="{key}">{value}</string>',
            s,
            count=1,
            flags=re.S,
        )
    path.write_text(s, encoding='utf-8')

# -----------------------------------------------------------------------------
# Home screen: expose one comprehensive lateral analysis. Studies, information,
# privacy and theme remain available. All other clinical-module launchers are hidden.
# -----------------------------------------------------------------------------
main = java_dir / 'MainActivity.java'
m = main.read_text(encoding='utf-8')
anchor = '        updateThemeButton(btnTheme);\n'
block = '''        updateThemeButton(btnTheme);\n\n        // Dedicated edition: one comprehensive lateral-skull analysis.\n        View sectionPanoramic = findViewById(R.id.sectionPanoramic);\n        if (sectionPanoramic != null) sectionPanoramic.setVisibility(View.GONE);\n        if (btnVertebral != null) btnVertebral.setVisibility(View.GONE);\n        if (btnAirway != null) btnAirway.setVisibility(View.GONE);\n        if (btnTweed != null) btnTweed.setVisibility(View.GONE);\n        if (btnPowell != null) btnPowell.setVisibility(View.GONE);\n        if (btnCvm != null) btnCvm.setVisibility(View.GONE);\n        if (btnLevandoski != null) btnLevandoski.setVisibility(View.GONE);\n        if (btnNolla != null) btnNolla.setVisibility(View.GONE);\n        if (btnResorption != null) btnResorption.setVisibility(View.GONE);\n        if (btnPanoramicReview != null) btnPanoramicReview.setVisibility(View.GONE);\n'''
if anchor not in m:
    raise RuntimeError('MainActivity identity insertion point not found')
m = m.replace(anchor, block, 1)
main.write_text(m, encoding='utf-8')

# -----------------------------------------------------------------------------
# Angular catalog: retain Steiner plus the clinically useful complementary
# measures generated by the full source pipeline, and add one key Ricketts
# growth-direction measure that requires only one additional point (Pt).
# -----------------------------------------------------------------------------
catalog = java_dir / 'MeasurementCatalog.java'
c = catalog.read_text(encoding='utf-8')
if 'Ricketts · Eje facial · Ba-N / Pt-Gn' not in c:
    method = re.compile(
        r'(public static List<MeasurementDefinition> steiner\(\) \{[\s\S]*?)(\n        return list;\n    \})',
        re.M,
    )
    addition = r'''
        // Ricketts: eje facial. Se añade en la edición lateral integral porque
        // es una de las medidas centrales del análisis y sólo agrega Pt.
        list.add(m(
                "Ricketts · Eje facial · Ba-N / Pt-Gn",
                TWO_LINES,
                p("Ba", "N", "Pt", "Gn"),
                86.5,
                93.5,
                "90° ± 3.5° · referencia clásica de Ricketts; sin ajuste por edad",
                "Marque Ba-N y el eje facial Pt-Gn. Pt corresponde al punto pterigoideo/foramen rotundum definido por Ricketts.",
                "Eje facial menor que la referencia: tendencia de crecimiento relativamente más vertical y/o mentón más posterior; interpretar con el resto del patrón.",
                "Eje facial dentro de 90° ± 3.5° de la referencia clásica.",
                "Eje facial mayor que la referencia: tendencia de crecimiento relativamente más horizontal/anterior; interpretar con el resto del patrón.",
                true
        ));
'''
    c, n = method.subn(lambda match: match.group(1) + addition + match.group(2), c, count=1)
    if n != 1:
        raise RuntimeError('Could not extend the standalone angular catalog')
catalog.write_text(c, encoding='utf-8')

# -----------------------------------------------------------------------------
# McNamara: the most useful standalone lateral measurements are primarily
# linear. They require calibration, but are optional: if Co / airway points are
# not placed, those rows simply do not appear in partial results.
# -----------------------------------------------------------------------------
linear = java_dir / 'LinearMeasurementCatalog.java'
l = linear.read_text(encoding='utf-8')
if 'McNamara · longitud maxilar efectiva · Co-A' not in l:
    method = re.compile(
        r'(public static List<LinearMeasurementDefinition> cephalometric\(\) \{[\s\S]*?)(\n        return list;\n    \})',
        re.M,
    )
    addition = r'''
        // McNamara: medidas seleccionadas por utilidad clínica. Las longitudes
        // dependen de edad, sexo y población; YOM no impone una falsa norma única.
        list.add(m(
                "McNamara · longitud maxilar efectiva · Co-A",
                DISTANCE,
                RANGE,
                p("Co", "A"),
                Double.NaN,
                Double.NaN,
                "Co-A en mm · comparar con referencia de McNamara apropiada para edad/sexo",
                "",
                "Longitud efectiva maxilar Co-A. Requiere calibración radiográfica; interpretar con edad, sexo, tamaño craneofacial y longitud mandibular.",
                ""
        ));

        list.add(m(
                "McNamara · longitud mandibular efectiva · Co-Gn",
                DISTANCE,
                RANGE,
                p("Co", "Gn"),
                Double.NaN,
                Double.NaN,
                "Co-Gn en mm · comparar con referencia de McNamara apropiada para edad/sexo",
                "",
                "Longitud efectiva mandibular Co-Gn. Requiere calibración; interpretar junto con Co-A y las relaciones sagitales.",
                ""
        ));

        list.add(m(
                "McNamara · altura facial anteroinferior · ENA-Me",
                DISTANCE,
                RANGE,
                p("ENA", "Me"),
                Double.NaN,
                Double.NaN,
                "ENA/ANS-Me en mm · referencia dependiente de edad/sexo",
                "",
                "Altura facial anteroinferior. Requiere calibración; no clasificar de forma aislada como aumentada o disminuida sin referencia apropiada.",
                ""
        ));

        // Las dos dimensiones faríngeas de McNamara también pueden obtenerse
        // desde la misma lateral, pero siguen siendo mediciones 2D descriptivas.
        list.add(m(
                "McNamara · vía aérea superior mínima",
                DISTANCE,
                RANGE,
                p("Faringe sup ant.", "Faringe sup post."),
                Double.NaN,
                Double.NaN,
                "Distancia mínima paladar blando-pared faríngea posterior · mm",
                "",
                "Dimensión anteroposterior mínima de la vía aérea superior en la lateral. No diagnostica obstrucción ni apnea por sí sola.",
                ""
        ));

        list.add(m(
                "McNamara · vía aérea inferior mínima",
                DISTANCE,
                RANGE,
                p("Faringe inf ant.", "Faringe inf post."),
                Double.NaN,
                Double.NaN,
                "Distancia mínima lengua-pared faríngea posterior · mm",
                "",
                "Dimensión anteroposterior mínima de la vía aérea inferior en la lateral. Interpretar como medida 2D y correlacionar clínicamente.",
                ""
        ));
'''
    l, n = method.subn(lambda match: match.group(1) + addition + match.group(2), l, count=1)
    if n != 1:
        raise RuntimeError('Could not extend the standalone McNamara catalog')
linear.write_text(l, encoding='utf-8')

# -----------------------------------------------------------------------------
# Landmark help for the two additional points introduced in this edition.
# Existing airway guidance is inherited from the audited complete application.
# -----------------------------------------------------------------------------
guide = java_dir / 'PointGuide.java'
p = guide.read_text(encoding='utf-8')
insert = '''        GUIDE.put("Co", "Condylion (Co): punto más posterosuperior del contorno de la cabeza condilar. Úselo para las longitudes efectivas Co-A y Co-Gn de McNamara; no lo confunda con el punto de proyección usado para SE.");\n        GUIDE.put("Pt", "Punto pterigoideo (Pt) de Ricketts: punto relacionado con la región del foramen rotundum/pterigomaxilar utilizado para construir el eje facial Pt-Gn. Si la referencia anatómica no es identificable con seguridad, omita esta medición en lugar de forzar el punto.");\n'''
if 'GUIDE.put("Co",' not in p:
    marker = '    static {\n'
    if marker not in p:
        raise RuntimeError('PointGuide static block not found')
    p = p.replace(marker, marker + insert, 1)
guide.write_text(p, encoding='utf-8')

# -----------------------------------------------------------------------------
# Standalone tests: verify the combined catalog is really present. Partial
# reports remain governed by the shared "only calculable measurements" logic.
# -----------------------------------------------------------------------------
test_dir = ROOT / 'app/src/test/java/com/cefalo/angulos'
test_dir.mkdir(parents=True, exist_ok=True)
test = test_dir / 'StandaloneLateralCatalogTest.java'
test.write_text(r'''package com.cefalo.angulos;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class StandaloneLateralCatalogTest {
    private static boolean hasAngular(String token) {
        for (MeasurementDefinition def : MeasurementCatalog.steiner()) {
            if (def.name.contains(token)) return true;
        }
        return false;
    }

    private static boolean hasLinear(String token) {
        for (LinearMeasurementDefinition def : LinearMeasurementCatalog.cephalometric()) {
            if (def.name.contains(token)) return true;
        }
        return false;
    }

    @Test public void combinesSteinerBjorkRickettsAndMcNamara() {
        assertTrue(hasAngular("SNA"));
        assertTrue(hasAngular("Ángulo de la silla"));
        assertTrue(hasAngular("Ricketts · Profundidad maxilar"));
        assertTrue(hasAngular("Ricketts · Eje facial"));
        assertTrue(hasLinear("Co-A"));
        assertTrue(hasLinear("Co-Gn"));
        assertTrue(hasLinear("vía aérea superior mínima"));
    }
}
''', encoding='utf-8')

# Guardrails against silently losing the requested behavior.
checks = {
    'package id': "applicationId 'com.yomceph.cefalometrico'" in gradle.read_text(encoding='utf-8'),
    'version 1.32': "versionName '1.32'" in gradle.read_text(encoding='utf-8'),
    'ricketts facial axis': 'Ricketts · Eje facial · Ba-N / Pt-Gn' in catalog.read_text(encoding='utf-8'),
    'mcnamara Co-A': 'McNamara · longitud maxilar efectiva · Co-A' in linear.read_text(encoding='utf-8'),
    'mcnamara airway': 'McNamara · vía aérea superior mínima' in linear.read_text(encoding='utf-8'),
    'Co guide': 'GUIDE.put("Co",' in guide.read_text(encoding='utf-8'),
    'Pt guide': 'GUIDE.put("Pt",' in guide.read_text(encoding='utf-8'),
}
missing = [name for name, ok in checks.items() if not ok]
if missing:
    raise RuntimeError('Standalone lateral conversion incomplete: ' + ', '.join(missing))

print('Standalone lateral app prepared: Steiner + selected Bjork/Jarabak + Ricketts + McNamara; optional-point partial results preserved.')
